export const ACTIONS = {
    SET_LOADING: 'SET_LOADING',
    SET_LANGUAGES: 'SET_LANGUAGES',
    SET_USER_LANGUAGE: 'SET_USER_LANGUAGE',
    SET_NETWORK_ERRORS: 'SET_NETWORK_ERRORS',
    SET_COMPILING: 'SET_COMPILING',
    SET_USER_OUTPUT: 'SET_USER_OUTPUT',
};